"use client";
import { useState } from "react";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xiSjIAI
 */
export default function Component() {
  const [messages, setMessages] = useState<string[]>([]);
  const moduleHash = "90a60a0dccc4ba24b84f93fb777af45cd7a70350";
  // const webSocket = new WebSocket("ws://substreams-sink-websockets-production.up.railway.app");
  const webSocket = new WebSocket("ws://localhost:3001");

  webSocket.onopen = () => {
    webSocket.send(moduleHash);
  };

  // if ( webSocket.readyState === WebSocket.OPEN ) {
  //   webSocket.send("moduleHash")
  // }
  webSocket.onmessage = event => {
    console.log(event.data);
    setMessages([...messages, event.data]);
  }
  // const messages = ["foo", "bar", "world"];
  return (
    <aside className="bg-black text-white p-6 rounded-lg w-full max-w-lg font-mono">
      <div className="flex justify-between items-center">
        <div className="flex space-x-2 text-red-500">
          <div className="w-3 h-3 rounded-full bg-red-500" />
          <div className="w-3 h-3 rounded-full bg-yellow-500" />
          <div className="w-3 h-3 rounded-full bg-green-500" />
        </div>
        <p className="text-sm">Substreams WebSockets</p>
      </div>
      <div className="mt-4">
        <p className="text-red-400">$ message {"<moduleHash>"}</p>
        <p className="text-green-400">$ {moduleHash}</p>
        {messages.map((message) => {
          return <p className="text-white">{message}</p>
        })}
      </div>
    </aside>
  )
}
